services:
  front:
    image: maratms-prod
    networks: [web]
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - TUNNEL_METRICS=0.0.0.0:49999
    networks: [web]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cloudflared", "version"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  web:
    driver: bridge
